version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5436:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: quickfruit
    networks:
      - quickfruit-network
  test-db:
    image: postgres:13
    ports:
      - 5437:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: quickfruit
    networks:
      - quickfruit-network
networks:
  quickfruit-network:
